"""add image_url column to rentals table

Revision ID: 2f58e49ee05a
Revises: 71e7584773fe
Create Date: 2023-07-17 16:31:35.008130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f58e49ee05a'
down_revision = '71e7584773fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
