"""creating new instance

Revision ID: 5f152cef1492
Revises: 
Create Date: 2023-07-19 10:09:03.808243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f152cef1492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rentals',
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sq_ft', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('availability_dates', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], name=op.f('fk_rentals_host_id_users')),
    sa.PrimaryKeyConstraint('rental_id')
    )
    op.create_table('shows',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('bandmates', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.user_id'], name=op.f('fk_shows_artist_id_users')),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('artist_bookings',
    sa.Column('artist_booking_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('accepted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.rental_id'], name=op.f('fk_artist_bookings_rental_id_rentals')),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], name=op.f('fk_artist_bookings_show_id_shows')),
    sa.PrimaryKeyConstraint('artist_booking_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.rental_id'], name=op.f('fk_reviews_rental_id_rentals')),
    sa.ForeignKeyConstraint(['writer_id'], ['users.user_id'], name=op.f('fk_reviews_writer_id_users')),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('artist_bookings')
    op.drop_table('shows')
    op.drop_table('rentals')
    op.drop_table('users')
    # ### end Alembic commands ###
