"""changed Review table to reviews

Revision ID: 71e7584773fe
Revises: a19a9cbbdb37
Create Date: 2023-07-17 16:12:16.268371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e7584773fe'
down_revision = 'a19a9cbbdb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['rentals.rental_id'], name=op.f('fk_reviews_accommodation_id_rentals')),
    sa.ForeignKeyConstraint(['writer_id'], ['users.user_id'], name=op.f('fk_reviews_writer_id_users')),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.drop_table('Review')
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('availability_dates',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.alter_column('availability_dates',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    op.create_table('Review',
    sa.Column('review_id', sa.INTEGER(), nullable=False),
    sa.Column('writer_id', sa.INTEGER(), nullable=True),
    sa.Column('accommodation_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['rentals.rental_id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.drop_table('reviews')
    # ### end Alembic commands ###
