"""changed accommodation_id column in reviews to rental_id

Revision ID: e59be26def31
Revises: 2f58e49ee05a
Create Date: 2023-07-18 10:23:54.051181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59be26def31'
down_revision = '2f58e49ee05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_accommodation_id_rentals', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_rental_id_rentals'), 'rentals', ['rental_id'], ['rental_id'])
        batch_op.drop_column('accommodation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_rental_id_rentals'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_accommodation_id_rentals', 'rentals', ['accommodation_id'], ['rental_id'])
        batch_op.drop_column('rental_id')

    # ### end Alembic commands ###
