"""change accommodations to rentals

Revision ID: ff7731dc6735
Revises: 3be262f6e6b8
Create Date: 2023-07-17 15:15:59.482304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7731dc6735'
down_revision = '3be262f6e6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sq_ft', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('availability_dates', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], name=op.f('fk_rentals_host_id_users')),
    sa.PrimaryKeyConstraint('rental_id')
    )
    op.drop_table('accommodations')
    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_Review_accommodation_id_rentals'), 'rentals', ['accommodation_id'], ['rental_id'])
        batch_op.drop_column('accomodations_id')

    with op.batch_alter_table('artist_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_artist_bookings_accomodations_id_accommodations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_artist_bookings_rental_id_rentals'), 'rentals', ['rental_id'], ['rental_id'])
        batch_op.drop_column('accomodations_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accomodations_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_artist_bookings_rental_id_rentals'), type_='foreignkey')
        batch_op.create_foreign_key('fk_artist_bookings_accomodations_id_accommodations', 'accommodations', ['accomodations_id'], ['accommodation_id'])
        batch_op.drop_column('rental_id')

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accomodations_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_Review_accommodation_id_rentals'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accommodations', ['accomodations_id'], ['accommodation_id'])
        batch_op.drop_column('accommodation_id')

    op.create_table('accommodations',
    sa.Column('accommodation_id', sa.INTEGER(), nullable=False),
    sa.Column('host_id', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('beds', sa.INTEGER(), nullable=True),
    sa.Column('baths', sa.FLOAT(), nullable=True),
    sa.Column('sq_ft', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('availability_dates', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], name='fk_accommodations_host_id_users'),
    sa.PrimaryKeyConstraint('accommodation_id')
    )
    op.drop_table('rentals')
    # ### end Alembic commands ###
